### ISSUE TITLE
Dead code?

### ISSUE THREAD

**Issue by martincapello** [WeylonSantana/Aseprite-Multiple-Export#1]
I think you could remove this else block: 
https://github.com/WeylonSantana/Aseprite-Multiple-Export/blob/22e185d1b35c7af663e39a2f1b51274972fe896f/Main.cs#L92-L95

**Comment by WeylonSantana** [comment]
I already tried to remove it, but for some reason the layerList count was greater than 0, even though there was no text in the textbox, so I added this line to fix the problem and that's what worked so far.

**Comment by martincapello** [comment]
I'm referring to the second else block:
https://github.com/WeylonSantana/Aseprite-Multiple-Export/blob/22e185d1b35c7af663e39a2f1b51274972fe896f/Main.cs#L87-L95

I believe that the second else is never executed...AFAIK when the `if` expression is false, it enters to the first `else` block. However I've never seen using two `else`s in one `if`clause. So I might be wrong.

**Comment by WeylonSantana** [comment]
Definitely haha I hadn't seen that, I'll fix it as soon as possible

**Comment by WeylonSantana** [comment]
solved in 74a208ecad6b5b6eb7311503ec6a9facdde726cd
